language: node_js
node_js:
- 4
- 6
- 8
- 10 
notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/aae9117008dad1557aac'
    on_success: change
    on_failure: always
    on_start: false
script: "npm run-script ci"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
